### ISSUE TITLE
[Feature Request] Aleeva DpsReport Upload Integration

### ISSUE THREAD

**Issue by itsmefox** [nbarrios/arcdps-uploader#11]
I'd like to have an Aleeva integration to import the processed dps.report reports and send them in an easy and fast way to a discord channel if neeeded. It would also be awesome if a server and channel selection based on Aleeva data could be used for this.

**Comment by nbarrios** [comment]
@itsmefox I know it's been a while but going to tackle this next. Do you know where the api docs are?
