### ISSUE TITLE
[Feature Request] Allow uploads from paths other than the standard log path

### ISSUE THREAD

**Issue by Rhett-Flanagan** [nbarrios/arcdps-uploader#15]
Currently, the plugin does not allow for uploading logs from paths other than the standard path for logs, so if you have your log path set to any other location the plugin doesn't function.

**Comment by nbarrios** [comment]
Fixed thanks to @cheahjs's note about pulling the log path straight from the arcdps ini. I'll put out a new release with this change after some testing.
