### ISSUE TITLE
Expose and standardise filenames in releases

### ISSUE THREAD

**Issue by Penthee** [nbarrios/arcdps-uploader#20]
So I was trying to build in support for this dll in my auto-updater script, trouble is the filename is different every time, taking version + build number it is unpredictable.
Any chance you could not put the dll in a zip and keep it to the same filename - don't put version in filename that's what metadata is for.
If they were set up like knoxfighter's https://github.com/knoxfighter/arcdps-killproof.me-plugin/releases that would be perfect. Thanks

**Comment by swatkins818** [comment]
I get around this in my own script, using github API. Here is my script below for your reference (really fork of someone else's script):

https://gist.github.com/swatkins818/4ba37f89dbfd9e2b6aa8bf4d7c90eee5

**Comment by nbarrios** [comment]
Now that I'm using Github actions to prepare releases, hopefully this is taken care of. ArcDPS now provides a way for extensions to ask to be updated themselves. I will try to update this to support that at some point.
