### ISSUE TITLE
[Feature Request] WvW Detailed Upload Option

### ISSUE THREAD

**Issue by Atros04** [nbarrios/arcdps-uploader#23]
Uploading any WvW log provides the standard WvW report, would like to see the option to upload to the detailed WvW report option provided by dps.report.

**Comment by nbarrios** [comment]
I have added an option to request detailed WvW logs in [v0.9.7](https://github.com/nbarrios/arcdps-uploader/releases/tag/v0.9.7). I didn't have a long log to test with, so you will just see a general error message if a log fails to parse due to length.
