### ISSUE TITLE
Expose dps.report user token or list where to find it

### ISSUE THREAD

**Issue by PathosV** [nbarrios/arcdps-uploader#24]
Please add a way to find the user token used by uploader,
this would be one way to easily integrate with other tools such as Aleeva, mentioned in #11

**Comment by punsii2** [comment]
Im currently working on this here: https://github.com/punsii2/arcdps-uploader/tree/user-token
I will try push this and other changes into the main Repo over the next days.

The change will currently:
 - automatically store the userToken and reuse them for every upload
 - display the userToken
 - allow you to set a custom userToken
 - allow you to disable the userToken (such that a new one will be created for every upload again)

One thing that i did not do yet do but which could probably be done is to add the userToken to the log-entries for each successful upload. But i think having one persistent token that is visible in the settings should be enough.

If you relay want this as fast as possible you can use the release from my fork
 It already works for me but some more testing/feedback would be appreciated.

**Comment by nbarrios** [comment]
Thanks @punsii2  for the pr. This is now merged and working in the [v0.9.7](https://github.com/nbarrios/arcdps-uploader/releases/tag/v0.9.7).
