### ISSUE TITLE
GW2Bot integration

### ISSUE THREAD

**Issue by JasonLucas** [nbarrios/arcdps-uploader#28]
Would be possible to add the Discord GW2Bot API Key automation integration?
Thank you!

**Comment by nbarrios** [comment]
@JasonLucas Took a quick look at this. Looks like gw2bot expects you post the raw evtc files to discord and it handles them from there. Can you explain how the api key comes into play and what kind of integration you were imagining?

**Comment by JasonLucas** [comment]
Sorry, I should have been more clear with my request, I didn't know there wasn't much information around about this feature. 
GW2Bot has a feature where you are able to link dps.report logs with your account and it also can automatically post logs on discord channels you choose with a very handy preview (plus some extra features for raid encounters). Here is the information I was able to find in the bot discord: 

> EVTC autoupload
> This one is a bit more complicated. What it does, is it allows third-party utilities that automatically upload logs to dps.report to integrate with GW2Bot, and have it post log overviews to channel. Even with no destinations selected, using this feature will still add the uploaded logs as links in /bosses
> 
> This command has two parts: /evtc api_key, which includes a tutorial and is used to generate an GW2Bot-API specific key to use with third party utilities. This does not give the application access to your account in any way.
> And /evtc autoupload This set of commands handle adding destinations (channels) for the logs to be posted in. The channels can be DM channels, and you can even set up channel-specific filter to only post logs there made while representing a specific guild.
> The only third-party log uploader utility which supports this API is currently PlenBot, and you can get the newest release here https://github.com/HardstuckGuild/PlenBotLogUploader/releases/tag/Release-69
> The API is, however, open, and if you develop a log uploader and want to add support for GW2Bot, check out the (rather bare) docs page at http://api.gw2bot.info/docs

I hope it helps somehow and thank you!

**Comment by nbarrios** [comment]
Thanks for finding that! Makes sense now. Might take me a bit but I should be able to integrate this.

**Comment by nbarrios** [comment]
@JasonLucas Got this working in v0.9.8. Let me know if you get a chance to test it. 

https://github.com/nbarrios/arcdps-uploader/releases/tag/v0.9.8.1

**Comment by JasonLucas** [comment]
Have been testing it for the past couple of days and it is working just fine, thanks for adding it!

**Comment by nbarrios** [comment]
Great! Thanks for the suggestion.
