### ISSUE TITLE
[BUG ?] Aleeva integration does not seem to be working. Also dps report still disabled ?

### ISSUE THREAD

**Issue by kratosangel** [nbarrios/arcdps-uploader#37]
Hello, so while trying to setup the uploader to link to Aleeva, however I dont know if im doing it right.
Ive set up a access code and pasted into uploader. However clicking on login does nothing, I won't get any information. I also tried a new access code, same story. Am I doing something wrong here ? I tried a Plenbot one or some other access codes but none of them seem to be working ?
Also dps report token is still disabled ? Any word about when it can work ?
![Screenshot_2023-08-01_164409](https://github.com/nbarrios/arcdps-uploader/assets/50416283/b2091063-1f6e-4139-93f1-a513b99887d9)
![Discord_745](https://github.com/nbarrios/arcdps-uploader/assets/50416283/f3381900-0af1-4940-83ce-54ac7d6bc80c)
![Discord_746](https://github.com/nbarrios/arcdps-uploader/assets/50416283/13d3f30c-b602-46c7-926e-910d040e9926)

**Comment by nbarrios** [comment]
I don't have much time to maintain this project (or play GW2 for that matter) so it may take me a while to respond.

I found the issue with Aleeva and will push out an update.

The dps.report token just needs to be enabled by hitting 'Enable`. You can then paste your token and hit save or one will be generated for you when you upload a log.

**Comment by kratosangel** [comment]
Hello, thanks for your answer. 
It does indeed work for dps report token, thanks for the explanation.
Gotcha for the Aleeva update incoming :)
