### ISSUE TITLE
Viewing logs ingame doesn't work

### ISSUE THREAD

**Issue by good-live** [nbarrios/arcdps-uploader#8]
It correctly uploads the logs, but when i want to view a log ingame it doesnt work (Neither clicking nor hovering over the "View" button does anything besides showing a small empty black rectangle). Screenshot attached.

![image](https://user-images.githubusercontent.com/10183190/99905538-aac8b780-2cd1-11eb-984d-a4af605270e8.png)

Using Version 0.9.27

**Comment by datatobridge** [comment]
I removed the built-in parser so log previews are gone for now. If I have time over the holidays I'll add an option to download the parsed data from dps.reports and show a preview in game. No timeline. I'll consider just removing the View button in the short term.

**Comment by good-live** [comment]
Hmm maybe a short-term solution would be to just open the log in the browser when the button is clicked.

**Comment by nbarrios** [comment]
You can now open logs in your browser using the view button.
