### ISSUE TITLE
Exception upon closing the game with ALT F4

### ISSUE THREAD

**Issue by good-live** [nbarrios/arcdps-uploader#9]
Whenever i close the game using ALT + F4 with this addon loaded it throws an exception (arcdps log attached)

[arcdps_lastcrash - onClose.log](https://github.com/datatobridge/arcdps-uploader/files/5579594/arcdps_lastcrash.-.onClose.log)

Using Version 0.9.27

**Comment by nbarrios** [comment]
I believe this was resolved by the threading fixes.
